# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='combineIdList',
            field=models.CharField(default='[0]', max_length=50, null=True),
        ),
    ]
