# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_combineidlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
    ]
