# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_response_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='combineIdList',
            field=models.CharField(default=[0], max_length=50),
        ),
    ]
