# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171007_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
