# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171007_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
