# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_messagelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='messageList',
            field=models.TextField(default='[]'),
        ),
    ]
