# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171008_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mailCheck',
        ),
        migrations.AlterField(
            model_name='user',
            name='combineIdList',
            field=models.TextField(default=None),
        ),
    ]
