# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171009_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keywordCheck',
            field=models.BooleanField(default=True),
        ),
    ]
