# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_user_keywordcheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='keywordCheck',
            new_name='doNextkeywordCheck',
        ),
    ]
