# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20171009_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doNextkeywordCheck',
            new_name='doNextKeywordCheck',
        ),
    ]
