# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20171009_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='delay',
            field=models.IntegerField(null=True),
        ),
    ]
