# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_log_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='delay',
            field=models.FloatField(null=True),
        ),
    ]
