# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_shuttle_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuttle',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
