# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20171102_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shuttle',
            old_name='validDateTime',
            new_name='validDate',
        ),
    ]
