# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20171102_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateField(auto_now_add=True)),
                ('text', models.CharField(max_length=60)),
            ],
        ),
    ]
