# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_miga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miga',
            old_name='text',
            new_name='menu',
        ),
    ]
