# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180314_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miga',
            name='id',
        ),
        migrations.AlterField(
            model_name='miga',
            name='dateTime',
            field=models.DateField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
