# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20180314_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semicon',
            fields=[
                ('dateTime', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=60)),
            ],
        ),
    ]
