# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_semicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sunfood',
            fields=[
                ('dateTime', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('menu_breakfast', models.CharField(max_length=60, null=True)),
                ('menu_lunch', models.CharField(max_length=60, null=True)),
                ('menu_dinner', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
