# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_sunfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=50)),
                ('menu', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.AlterField(
            model_name='sunfood',
            name='menu_breakfast',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sunfood',
            name='menu_dinner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sunfood',
            name='menu_lunch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
