# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20180329_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendmenu',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
